from util.dataclasses import RoleCategory

COURSE_TRACKER_ROLE_CATEGORY = RoleCategory("COURSE TRACKERS")
TA_ROLE_CATEGORY = RoleCategory("TEACHING ASSISTANT")
PERSONAL_ROLE_CATEGORY = RoleCategory("PERSONAL")
COMMUNITY_ROLE_CATEGORY = RoleCategory("COMMUNITY")
CLASSES_ROLE_CATEGORY = RoleCategory("CLASSES")
BOTS_ROLE_CATEGORY = RoleCategory("BOTS")
